// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.s305089.bookstore;

import com.s305089.bookstore.Category;

privileged aspect Category_Roo_JavaBean {
    
    public String Category.getName() {
        return this.Name;
    }
    
    public void Category.setName(String Name) {
        this.Name = Name;
    }
    
}
