// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.s305089.bookstore.email;

import com.s305089.bookstore.email.ContactInfo;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ContactInfo_Roo_Configurable {
    
    declare @type: ContactInfo: @Configurable;
    
}
